# Generated by Django 5.1.6 on 2025-02-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_community_only',
            field=models.BooleanField(default=False),
        ),
    ]
