# Generated by Django 5.1.6 on 2025-02-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('family_name', models.CharField(blank=True, max_length=255)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('how_to_grow', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flower_images/')),
            ],
        ),
    ]
